#> iphone Stash Private Config 
#  iPhone Stash è‡ªç”¨é…ç½®ï¼Œä»…ä¾›å‚è€ƒ
#  è§„åˆ™ä¸»è¦ä½¿ç”¨äº† geosite & geoip
#  geoip ä½¿ç”¨äº†ç¬¬ä¸‰æ–¹æ•°æ®åº“
#  geosite å—é™äº Stash ä¸æ”¯æŒæ›´æ”¹ï¼Œä½¿ç”¨äº†åŸç‰ˆ
#>
#> âœï¸ æ´‹ san èŠ‹
#> ğŸ•™ last updateï¼š2025-12-03

# å…¨çƒç›´è¿è‡ªå®šä¹‰åç§°
direct_policy: &direct_policy "ğŸ’š å…¨çƒç›´è¿"

# å›¾æ ‡ä½¿ç”¨
# å›¾æ ‡åº“ @Koolson: https://github.com/Koolson/Qure/tree/master/IconSet
# ä¸€é”®å®‰è£…åœ°å€: stash://install-icon-set?url=https://fastly.jsdelivr.net/gh/Koolson/Qure/Other/QureColor-All.json
# å…¶ä»–å›¾æ ‡åº“
# Color+ @Orz-3 https://github.com/Orz-3/mini
icon_url:
  # æ——æ ‡
  hk: &icon_hk "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png"
  tw: &icon_tw "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/China.png"
  jp: &icon_jp "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png"
  sg: &icon_sg "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png"
  us: &icon_us "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png"
  # å¸¸ç”¨ç½‘ç«™
  google: &icon_google "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Google_Search.png"
  youtube: &icon_youtube "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png"
  telegram: &icon_telegram "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Telegram.png"
  # å…¶ä»–
  cat: &icon_cat "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Cat.png"
  proxy: &icon_proxy "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Proxy.png"
  final: &icon_final "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Final.png"
  static: &icon_static "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Static.png"
  amytelecom: &icon_amytelecom "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/AmyTelecom.png"

mode: rule
log-level: info

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fake-ip-filter:
    - geosite:connectivity-check
    - geosite:private
  nameserver-policy:
    geosite:cn: https://dns.alidns.com/dns-query

proxies:
  - name: *direct_policy
    type: DIRECT

proxy-providers:
  proxy-providers_1:
    url: proxy-providers_1-url
    filter: "^(?!.*æµ·å¤–).*"
    interval: 86400

proxy-groups:
  - &proxy-groups_config
    name: é€‰æ‹©ä»£ç†
    icon: *icon_cat
    type: select
    proxies:
      - é¦™æ¸¯è‡ªåŠ¨
      - å°æ¹¾è‡ªåŠ¨
      - æ—¥æœ¬è‡ªåŠ¨
      - ç¾å›½è‡ªåŠ¨
      - ç‹®åŸè‡ªåŠ¨
      - *direct_policy
    interval: 600
    lazy: true

  - <<: *proxy-groups_config
    name: Telegram
    icon: *icon_telegram

  - <<: *proxy-groups_config
    name: YouTube
    icon: *icon_youtube

  - <<: *proxy-groups_config
    name: Google
    icon: *icon_google

  - <<: *proxy-groups_config
    name: æ‰‹åŠ¨é€‰æ‹©
    icon: *icon_static
    proxies:
      - *direct_policy
      - å…¶ä»–åŒºåŸŸ

  - <<: *proxy-groups_config
    name: é»˜è®¤
    icon: *icon_final
    proxies:
      - *direct_policy
      - é€‰æ‹©ä»£ç†

    # åŸºäºåŒºåŸŸçš„ç­–ç•¥
  - &proxy-groups_url-test_config
    <<: *proxy-groups_config
    name: é¦™æ¸¯è‡ªåŠ¨
    filter: "(?i)(æ¾³é—¨|ğŸ‡²ğŸ‡´|æ¸¯|ğŸ‡­ğŸ‡°|hk|hong)"
    icon: *icon_hk
    type: url-test
    proxies: null
    include-all: true

  - <<: *proxy-groups_url-test_config
    name: å°æ¹¾è‡ªåŠ¨
    filter: "(?i)(å°|ğŸ‡¹ğŸ‡¼|æ¹¾|tw|taiwan)"
    icon: *icon_tw

  - <<: *proxy-groups_url-test_config
    name: æ—¥æœ¬è‡ªåŠ¨
    filter: "(?i)(æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|å¤§é˜ª|jp|japan)"
    icon: *icon_jp

  - <<: *proxy-groups_url-test_config
    name: ç‹®åŸè‡ªåŠ¨
    filter: "(?i)(æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|sg|singapore)"
    icon: *icon_sg

  - <<: *proxy-groups_url-test_config
    name: ç¾å›½è‡ªåŠ¨
    filter: "(?i)(ç¾|ğŸ‡ºğŸ‡²|us|states|america|ç¡…)"
    icon: *icon_us

  - <<: *proxy-groups_url-test_config
    filter: (?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¹ğŸ‡¼|ğŸ‡¯ğŸ‡µ|ğŸ‡°ğŸ‡·|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hong|å°|tw|taiwan|æ—¥æœ¬|jp|japan|éŸ©|kr|korea|ç¾|us|states|æ–°åŠ å¡|sg|singapore|ç¡…è°·|ç¡…))
    name: å…¶ä»–åŒºåŸŸ
    icon: *icon_amytelecom

rules:
  - GEOSITE,private,*direct_policy
  - GEOSITE,bilibili,*direct_policy
  - GEOSITE,spotify,é¦™æ¸¯è‡ªåŠ¨
  - GEOSITE,github,é¦™æ¸¯è‡ªåŠ¨
  - GEOSITE,microsoft,*direct_policy
  - GEOSITE,speedtest,*direct_policy
  - GEOSITE,meta,é¦™æ¸¯è‡ªåŠ¨
  - GEOSITE,cloudflare,é¦™æ¸¯è‡ªåŠ¨
  - GEOSITE,telegram,Telegram
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,apple,*direct_policy
  - GEOSITE,geolocation-!cn@cn,*direct_policy
  - GEOSITE,geolocation-!cn,é€‰æ‹©ä»£ç†
  - GEOSITE,geolocation-cn@!cn,é€‰æ‹©ä»£ç†
  - GEOSITE,geolocation-cn,*direct_policy
  - GEOSITE,tld-cn,*direct_policy
  - GEOIP,private,*direct_policy
  - GEOIP,apple,*direct_policy
  - GEOIP,telegram,Telegram
  - GEOIP,cloudflare,é¦™æ¸¯è‡ªåŠ¨
  - GEOIP,google,Google
  - GEOIP,bilibili,*direct_policy
  - GEOIP,cn,*direct_policy
  - MATCH,é»˜è®¤
